-- =====================================================================
-- Módulo Benefícios (cestas básicas) — fundação do schema.
--
-- Convenções desta migration:
--   * Banco alvo: PostgreSQL (Supabase) — como o CLAUDE.md do módulo sempre
--     pediu. Rodou em MySQL até a migração pra Supabase; ver histórico do
--     git se precisar da versão MySQL.
--   * snake_case, em português, como o restante do módulo.
--   * Nenhuma linha é fisicamente apagada nas tabelas de domínio: usamos as
--     colunas `ativo` (beneficiario/voluntario) e `cancelada` (retirada_cesta).
--
-- Índice único condicional (retirada_cesta):
--   O modelo pede "no máximo 1 retirada válida por beneficiário/mês civil".
--   O Postgres tem índice único parcial nativo (`WHERE cancelada = false`),
--   mas optamos pelo mesmo artifício de coluna gerada usado quando o projeto
--   ainda rodava em MySQL (que não tem índice parcial): uma coluna gerada
--   `mes_referencia_ativo`, que replica `mes_referencia` somente quando a
--   retirada está ativa e vira NULL quando cancelada. Um índice único em
--   (beneficiario_id, mes_referencia_ativo) garante a regra, porque o
--   Postgres também trata múltiplos NULLs como valores distintos em índices
--   únicos — quantas retiradas canceladas existirem para o mesmo
--   beneficiário/mês, elas nunca colidem entre si nem bloqueiam uma nova
--   tentativa válida. Essa coluna não é mapeada na entidade JPA (é somente
--   um artifício de banco para sustentar a constraint).
-- =====================================================================

CREATE TABLE voluntario (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf                 VARCHAR(11)  NULL,
    nome                VARCHAR(150) NOT NULL,
    telefone            VARCHAR(20)  NULL,
    email               VARCHAR(150) NULL,
    area_atuacao        VARCHAR(120) NULL,
    setor               VARCHAR(120) NULL,
    is_padrinho         BOOLEAN      NOT NULL DEFAULT FALSE,
    disponibilidade     VARCHAR(200) NULL,
    observacao          TEXT         NULL,
    ativo               BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em           TIMESTAMP    NOT NULL,
    criado_por          VARCHAR(120) NOT NULL,
    atualizado_em       TIMESTAMP    NULL,
    atualizado_por      VARCHAR(120) NULL,
    CONSTRAINT uk_voluntario_cpf UNIQUE (cpf)
);

CREATE INDEX idx_voluntario_nome ON voluntario (nome);
CREATE INDEX idx_voluntario_is_padrinho ON voluntario (is_padrinho);


CREATE TABLE beneficiario (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpf                             VARCHAR(11)  NOT NULL,
    nome                            VARCHAR(150) NOT NULL,
    data_nascimento                 DATE         NULL,
    telefone                        VARCHAR(20)  NULL,
    email                           VARCHAR(150) NULL,
    nome_mae                        VARCHAR(150) NULL,
    nome_conjuge                    VARCHAR(150) NULL,
    cpf_conjuge                     VARCHAR(11)  NULL,
    pessoas_residencia              INT          NULL,
    tem_filhos                      VARCHAR(20)  NULL,
    quantidade_filhos               INT          NULL,
    idades_filhos                   TEXT         NULL,
    filhos_com_deficiencia          VARCHAR(20)  NULL,
    descricao_deficiencia_filhos    TEXT         NULL,
    familiar_com_deficiencia        VARCHAR(20)  NULL,
    descricao_deficiencia_familiar  TEXT         NULL,
    tem_trabalho                    VARCHAR(20)  NULL,
    renda_familiar                  DECIMAL(10,2) NULL,
    status                          VARCHAR(40)  NOT NULL,
    prazo_final_beneficio           DATE         NULL,
    padrinho_id                     BIGINT       NULL,
    observacao                      TEXT         NULL,
    ativo                           BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em                       TIMESTAMP    NOT NULL,
    criado_por                      VARCHAR(120) NOT NULL,
    atualizado_em                   TIMESTAMP    NULL,
    atualizado_por                  VARCHAR(120) NULL,
    CONSTRAINT uk_beneficiario_cpf UNIQUE (cpf),
    CONSTRAINT fk_beneficiario_padrinho FOREIGN KEY (padrinho_id) REFERENCES voluntario (id)
);

CREATE INDEX idx_beneficiario_nome ON beneficiario (nome);
CREATE INDEX idx_beneficiario_status ON beneficiario (status);
CREATE INDEX idx_beneficiario_prazo_final_beneficio ON beneficiario (prazo_final_beneficio);
CREATE INDEX idx_beneficiario_padrinho_id ON beneficiario (padrinho_id);


CREATE TABLE beneficiario_endereco (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beneficiario_id     BIGINT       NOT NULL,
    endereco_completo   TEXT         NULL,
    cep                 VARCHAR(8)   NULL,
    rua                 VARCHAR(150) NULL,
    numero              VARCHAR(20)  NULL,
    complemento         VARCHAR(100) NULL,
    bairro              VARCHAR(100) NULL,
    cidade              VARCHAR(100) NULL,
    uf                  CHAR(2)      NULL,
    chave_residencia    VARCHAR(200) NULL,
    criado_em           TIMESTAMP    NOT NULL,
    criado_por          VARCHAR(120) NOT NULL,
    atualizado_em       TIMESTAMP    NULL,
    atualizado_por      VARCHAR(120) NULL,
    CONSTRAINT uk_beneficiario_endereco_beneficiario UNIQUE (beneficiario_id),
    CONSTRAINT fk_beneficiario_endereco_beneficiario FOREIGN KEY (beneficiario_id) REFERENCES beneficiario (id)
);

CREATE INDEX idx_beneficiario_endereco_chave_residencia ON beneficiario_endereco (chave_residencia);


CREATE TABLE retirada_cesta (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beneficiario_id         BIGINT       NOT NULL,
    mes_referencia          DATE         NOT NULL,
    data_retirada           TIMESTAMP    NOT NULL,
    quantidade_cestas       INT          NOT NULL DEFAULT 1,
    tipo_retirante          VARCHAR(25)  NOT NULL,
    retirante_nome          VARCHAR(150) NOT NULL,
    retirante_cpf           VARCHAR(11)  NULL,
    retirante_vinculo       VARCHAR(120) NULL,
    retirado_por_padrinho   BOOLEAN      NOT NULL DEFAULT FALSE,
    padrinho_id             BIGINT       NULL,
    voluntario_entrega_id   BIGINT       NULL,
    registrado_por          VARCHAR(120) NOT NULL,
    observacao              TEXT         NULL,
    cancelada               BOOLEAN      NOT NULL DEFAULT FALSE,
    motivo_cancelamento     TEXT         NULL,
    cancelada_em            TIMESTAMP    NULL,
    cancelada_por           VARCHAR(120) NULL,
    criado_em               TIMESTAMP    NOT NULL,
    criado_por              VARCHAR(120) NOT NULL,
    atualizado_em           TIMESTAMP    NULL,
    atualizado_por          VARCHAR(120) NULL,
    -- ver nota no cabeçalho do arquivo sobre esta coluna
    mes_referencia_ativo    DATE GENERATED ALWAYS AS (CASE WHEN cancelada = FALSE THEN mes_referencia ELSE NULL END) STORED,
    CONSTRAINT fk_retirada_beneficiario FOREIGN KEY (beneficiario_id) REFERENCES beneficiario (id),
    CONSTRAINT fk_retirada_padrinho FOREIGN KEY (padrinho_id) REFERENCES voluntario (id),
    CONSTRAINT fk_retirada_voluntario_entrega FOREIGN KEY (voluntario_entrega_id) REFERENCES voluntario (id),
    CONSTRAINT uk_retirada_beneficiario_mes_ativo UNIQUE (beneficiario_id, mes_referencia_ativo)
);

CREATE INDEX idx_retirada_data_retirada ON retirada_cesta (data_retirada);
CREATE INDEX idx_retirada_mes_referencia ON retirada_cesta (mes_referencia);
CREATE INDEX idx_retirada_padrinho_id ON retirada_cesta (padrinho_id);
CREATE INDEX idx_retirada_voluntario_entrega_id ON retirada_cesta (voluntario_entrega_id);


CREATE TABLE retirada_confirmacao (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    retirada_id         BIGINT       NOT NULL,
    codigo_aviso        VARCHAR(60)  NOT NULL,
    severidade          VARCHAR(20)  NOT NULL,
    mensagem            TEXT         NOT NULL,
    referencia_id       BIGINT       NULL,
    confirmado_por      VARCHAR(120) NOT NULL,
    confirmado_em       TIMESTAMP    NOT NULL,
    justificativa       TEXT         NULL,
    CONSTRAINT fk_retirada_confirmacao_retirada FOREIGN KEY (retirada_id) REFERENCES retirada_cesta (id)
);

CREATE INDEX idx_retirada_confirmacao_retirada ON retirada_confirmacao (retirada_id);


CREATE TABLE beneficios_auditoria (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidade        VARCHAR(80)  NOT NULL,
    entidade_id     BIGINT       NULL,
    acao            VARCHAR(20)  NOT NULL,
    usuario         VARCHAR(120) NOT NULL,
    perfil          VARCHAR(40)  NULL,
    ip              VARCHAR(45)  NULL,
    dados_antes     TEXT         NULL,
    dados_depois    TEXT         NULL,
    data_hora       TIMESTAMP    NOT NULL
);

CREATE INDEX idx_beneficios_auditoria_entidade ON beneficios_auditoria (entidade, entidade_id);
CREATE INDEX idx_beneficios_auditoria_data_hora ON beneficios_auditoria (data_hora);
