-- Etapa 4: histórico de vínculo padrinho <-> beneficiário.
-- Trocar de padrinho nunca apaga o vínculo anterior — só encerra (fim = hoje),
-- para relatórios antigos continuarem corretos (ver CLAUDE.md do módulo).

CREATE TABLE beneficiario_padrinho_historico (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    beneficiario_id BIGINT       NOT NULL,
    voluntario_id   BIGINT       NOT NULL,
    inicio          DATE         NOT NULL,
    fim             DATE         NULL,
    motivo_fim      TEXT         NULL,
    criado_em       TIMESTAMP    NOT NULL,
    criado_por      VARCHAR(120) NOT NULL,
    atualizado_em   TIMESTAMP    NULL,
    atualizado_por  VARCHAR(120) NULL,
    CONSTRAINT fk_apadrinhamento_beneficiario FOREIGN KEY (beneficiario_id) REFERENCES beneficiario (id),
    CONSTRAINT fk_apadrinhamento_voluntario FOREIGN KEY (voluntario_id) REFERENCES voluntario (id)
);

CREATE INDEX idx_apadrinhamento_beneficiario ON beneficiario_padrinho_historico (beneficiario_id, fim);
CREATE INDEX idx_apadrinhamento_voluntario ON beneficiario_padrinho_historico (voluntario_id, fim);
